$(document).ready(function(){console.log('READY');setInterval(function(){if($(".form-date").length){$(".form-date").each(function(){$(this).attr('type','text').addClass('customDatePicker');$(this).attr('readonly','readonly');var placeHolderValue=$(this).parent().find('label').text();if(placeHolderValue=='Search by date'||placeHolderValue=='Search By Date'){placeHolderValue='To Date';$(this).addClass('toDateSetting');}
$(this).attr('placeholder',placeHolderValue);$(this).parent().find('label').addClass('invisible');$(this).removeClass('customDatePicker');$(this).addClass('customDatePickerJqui');if($(this).attr('id')=="edit-field-date-press-releases-value-1"){$(this).attr('placeholder','To Date');$(this).addClass('toDateSetting');}});if($(".customDatePickerJqui").length){$(".customDatePickerJqui").datepicker({dateFormat:"dd/mm/yy",changeMonth:true,changeYear:true,autoclose:true,onClose:function(selectedDate){$(".toDateSetting").datepicker("option","minDate",selectedDate);}});}
$.urlParam=function(name){var results=new RegExp('[\?&]'+name+'=([^&#]*)').exec(window.location.href);if(results==null){return null;}
else{return results[1]||0;}}
if($('input[name="field_events_date_range_value"]').length&&$('input[name="field_events_date_range_end_value"]').length){var param1=$.urlParam("field_events_date_range_value");var param2=$.urlParam("field_events_date_range_end_value");}
else if($('input[name="field_date_press_releases_value"]').length&&$('input[name="field_date_press_releases_value_1"]').length){var param1=$.urlParam("field_date_press_releases_value");var param2=$.urlParam("field_date_press_releases_value_1");}
else if($('input[name="field_articles_date_value"]').length&&$('input[name="field_articles_date_value_1"]').length){var param1=$.urlParam("field_articles_date_value");var param2=$.urlParam("field_articles_date_value_1");}
else if($('input[name="field_date_speeches_value"]').length&&$('input[name="field_date_speeches_value_1"]').length){var param1=$.urlParam("field_date_speeches_value");var param2=$.urlParam("field_date_speeches_value_1");}
else if($('input[name="field_video_gallery_date_value"]').length&&$('input[name="field_video_gallery_date_value_1"]').length){var param1=$.urlParam("field_video_gallery_date_value");var param2=$.urlParam("field_video_gallery_date_value_1");}
else if($('input[name="field_bjp_live_date_value"]').length&&$('input[name="field_bjp_live_date_value_1"]').length){var param1=$.urlParam("field_bjp_live_date_value");var param2=$.urlParam("field_bjp_live_date_value_1");}
else if($('input[name="field_date_photo_gallery_value"]').length&&$('input[name="field_date_photo_gallery_value_1"]').length){var param1=$.urlParam("field_date_photo_gallery_value");var param2=$.urlParam("field_date_photo_gallery_value_1");}else{var param1=null;var param2=null}
if(param1!=null&&param1!='0'&&param2!=null&&param2!='0'){var res1=decodeURIComponent(param1);var res2=decodeURIComponent(param2);var d1=res1.slice(0,10).split('/');var p1=d1[1]+'/'+d1[0]+'/'+d1[2];var d2=res2.slice(0,10).split('/');var p2=d2[1]+'/'+d2[0]+'/'+d2[2];console.log("param1-"+p1+"-");console.log("param2-"+p2+"-");}else{}
if($('input[name="field_events_date_range_value"]').length&&$('input[name="field_events_date_range_end_value"]').length){var param1=$.urlParam("field_events_date_range_value");var param2=$.urlParam("field_events_date_range_end_value");if(param1!=null&&param1!='0'){$('input[name="field_events_date_range_value"]').val(decodeURIComponent(param1));}else{}
if(param2!=null&&param2!='0'){$('input[name="field_events_date_range_end_value"]').val(decodeURIComponent(param2));}else{}}
if($('input[name="field_date_press_releases_value"]').length&&$('input[name="field_date_press_releases_value_1"]').length){var param1=$.urlParam("field_date_press_releases_value");var param2=$.urlParam("field_date_press_releases_value_1");if(param1!=null&&param1!='0'){$('input[name="field_date_press_releases_value"]').val(decodeURIComponent(param1));}else{}
if(param2!=null&&param2!='0'){$('input[name="field_date_press_releases_value_1"]').val(decodeURIComponent(param2));}else{}}
if($('input[name="field_articles_date_value"]').length&&$('input[name="field_articles_date_value_1"]').length){var param1=$.urlParam("field_articles_date_value");var param2=$.urlParam("field_articles_date_value_1");if(param1!=null&&param1!='0'){$('input[name="field_articles_date_value"]').val(decodeURIComponent(param1));}else{}
if(param2!=null&&param2!='0'){$('input[name="field_articles_date_value_1"]').val(decodeURIComponent(param2));}else{}}
if($('input[name="field_date_speeches_value"]').length&&$('input[name="field_date_speeches_value_1"]').length){var param1=$.urlParam("field_date_speeches_value");var param2=$.urlParam("field_date_speeches_value_1");if(param1!=null&&param1!='0'){$('input[name="field_date_speeches_value"]').val(decodeURIComponent(param1));}else{}
if(param2!=null&&param2!='0'){$('input[name="field_date_speeches_value_1"]').val(decodeURIComponent(param2));}else{}}
if($('input[name="field_video_gallery_date_value"]').length&&$('input[name="field_video_gallery_date_value_1"]').length){var param1=$.urlParam("field_video_gallery_date_value");var param2=$.urlParam("field_video_gallery_date_value_1");if(param1!=null&&param1!='0'){$('input[name="field_video_gallery_date_value"]').val(decodeURIComponent(param1));}else{}
if(param2!=null&&param2!='0'){$('input[name="field_video_gallery_date_value_1"]').val(decodeURIComponent(param2));}else{}}
if($('input[name="field_bjp_live_date_value"]').length&&$('input[name="field_bjp_live_date_value_1"]').length){var param1=$.urlParam("field_bjp_live_date_value");var param2=$.urlParam("field_bjp_live_date_value_1");if(param1!=null&&param1!='0'){$('input[name="field_bjp_live_date_value"]').val(decodeURIComponent(param1));}else{}
if(param2!=null&&param2!='0'){$('input[name="field_bjp_live_date_value_1"]').val(decodeURIComponent(param2));}else{}}
if($('input[name="field_date_photo_gallery_value"]').length&&$('input[name="field_date_photo_gallery_value_1"]').length){var param1=$.urlParam("field_date_photo_gallery_value");var param2=$.urlParam("field_date_photo_gallery_value_1");if(param1!=null&&param1!='0'){$('input[name="field_date_photo_gallery_value"]').val(decodeURIComponent(param1));}else{}
if(param2!=null&&param2!='0'){console.log(param2);$('input[name="field_date_photo_gallery_value_1"]').val(decodeURIComponent(param2));}else{}}}else{}},3000);});